### ISSUE TITLE
yarn serve error

### ISSUE THREAD

**Issue by remony4** [remony4/remony_website#3]
```yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 118.62s.

C:\Users\RGBA\Documents\GitHub\remony_website>yarn serv
yarn run v1.22.10
error Command "serv" not found. Did you mean "serve"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\RGBA\Documents\GitHub\remony_website>yarn serve
yarn run v1.22.10
$ eleventy --serve
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk (and markdown) template ./art/connect_experience/index.md

`TemplateContentRenderError` was thrown
> (./art/connect_experience/index.md)
  Template render error: (C:\Users\RGBA\Documents\GitHub\remony_website\_includes\gallery.njk)
  EleventyShortcodeError: Error with Nunjucks shortcode `gallery`

`Template render error` was thrown
> ENOENT: no such file or directory, stat 'art\connect_experience\(1).JPG'

`Template render error` was thrown:
    Error: ENOENT: no such file or directory, stat 'art\connect_experience\(1).JPG'
        at Object.statSync (fs.js:1086:3)
        at Object.statSync (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\graceful-fs\polyfills.js:312:16)
        at queueImage (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\@11ty\eleventy-img\img.js:358:33)
        at C:\Users\RGBA\Documents\GitHub\remony_website\.eleventy.js:89:26
        at Array.map (<anonymous>)
        at Object.galleryShortCode (C:\Users\RGBA\Documents\GitHub\remony_website\.eleventy.js:88:12)
        at Object.<anonymous> (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\@11ty\eleventy\src\BenchmarkGroup.js:30:26)
        at ShortcodeFunction.run (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:120:14)
        at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:10:35)
        at Template.render (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\nunjucks\src\environment.js:552:10)
Copied 33 files / Wrote 0 files in 4.01 seconds (v0.11.1)
Watching…
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:8080
    External: http://10.0.75.1:8080
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ----------------------------------
[Browsersync] Serving files from: _site
Uncaught exception: (more in DEBUG output)
> ENOENT: no such file or directory, open '_site/404.html'

`Error` was thrown:
    Error: ENOENT: no such file or directory, open '_site/404.html'
        at Object.openSync (fs.js:476:3)
        at Object.readFileSync (fs.js:377:35)
        at Object.ready (C:\Users\RGBA\Documents\GitHub\remony_website\.eleventy.js:135:32)
        at BrowserSync.callback (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\browser-sync.js:51:12)
        at C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\browser-sync.js:228:12
        at C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\utils.js:276:21
        at executeTask (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\browser-sync.js:136:13)
        at Object.initUserPlugins [as fn] (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\async.js:294:9)
        at C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\browser-sync.js:120:14
        at iterate (C:\Users\RGBA\Documents\GitHub\remony_website\node_modules\browser-sync\dist\utils.js:268:9)
```

**Comment by faebser** [comment]
Hm, so wie es aussieht, findet das system bilder die eine grossgeschriebene datei extensions (in diesem fall JPG) habe nicht. Ich habe ein issue für eleventy erfasst.

**Comment by faebser** [comment]
Bitte vergiss was ich in obigem Kommentar geschrieben habe, das Problem ist, dass die Bilder unter ```art/conncet_experience``` ein Leerzeichen vorangestellt haben. (z.b. ``` 24.JPG``` statt ```24.JPG```). Wird das Leerzeichen gelöscht, klappt alles wunderbar.
